### ISSUE TITLE
Cannot extend from packages in node_modules

### ISSUE THREAD

**Issue by hpersson** [bahmutov/cypress-extends#22]
Our project keeps all config in a separate package that individual repos import/extend from. External packages located in the node_modules directory are not resolved properly when trying to use the cypress-extends plugin.

cypress.json
```
    ...
    extends: "@some-lib/cypress-config"
    ....
```

[potential solution](https://github.com/bahmutov/cypress-extends/pull/21)

**Comment by bahmutov** [comment]
Let me check it, it would be a nice extension

**Comment by bahmutov** [comment]
Should be resolved in https://github.com/bahmutov/cypress-extends/pull/21
